// Code generated by MockGen. DO NOT EDIT.
// Source: ./llm.go
//
// Generated by this command:
//
//	mockgen -source=./llm.go -destination=../mocks/llm.mock.go -package=mocks -typed Handler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/ai-gateway-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Stream mocks base method.
func (m *MockHandler) Stream(ctx context.Context, req domain.StreamRequest) (chan domain.StreamEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, req)
	ret0, _ := ret[0].(chan domain.StreamEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockHandlerMockRecorder) Stream(ctx, req any) *MockHandlerStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockHandler)(nil).Stream), ctx, req)
	return &MockHandlerStreamCall{Call: call}
}

// MockHandlerStreamCall wrap *gomock.Call
type MockHandlerStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlerStreamCall) Return(arg0 chan domain.StreamEvent, arg1 error) *MockHandlerStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlerStreamCall) Do(f func(context.Context, domain.StreamRequest) (chan domain.StreamEvent, error)) *MockHandlerStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlerStreamCall) DoAndReturn(f func(context.Context, domain.StreamRequest) (chan domain.StreamEvent, error)) *MockHandlerStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
