// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/ecodeclub/ai-gateway-go/internal/admin"
	"github.com/ecodeclub/ai-gateway-go/internal/grpc"
	"github.com/ecodeclub/ai-gateway-go/internal/repository"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/cache"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/dao"
	"github.com/ecodeclub/ai-gateway-go/internal/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	chatDAO := dao.NewChatDAO(db)
	cmdable := InitRedis()
	chatCache := cache.NewChatCache(cmdable)
	chatRepo := repository.NewChatRepo(chatDAO, chatCache)
	handler := initLLMHandler()
	chatService := service.NewChatService(chatRepo, handler)
	chatServer := grpc.NewChatServer(chatService)
	component := InitGrpcServer(chatServer)
	provider := InitSession()
	promptDAO := dao.NewPromptDAO(db)
	promptRepo := repository.NewPromptRepo(promptDAO)
	promptService := service.NewPromptService(promptRepo)
	promptHandler := admin.NewPromptHandler(promptService)
	bizConfigDAO := dao.NewBizConfigDAO(db)
	bizConfigRepository := repository.NewBizConfigRepository(bizConfigDAO)
	bizConfigService := service.NewBizConfigService(bizConfigRepository)
	bizConfigHandler := admin.NewBizConfigHandler(bizConfigService)
	eginComponent := InitGin(provider, promptHandler, bizConfigHandler)
	app := &App{
		GrpcSever: component,
		GinServer: eginComponent,
	}
	return app
}
