// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/ecodeclub/ai-gateway-go/internal/admin"
	"github.com/ecodeclub/ai-gateway-go/internal/grpc"
	"github.com/ecodeclub/ai-gateway-go/internal/repository"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/cache"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/dao"
	"github.com/ecodeclub/ai-gateway-go/internal/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	chatDAO := dao.NewChatDAO(db)
	cmdable := InitRedis()
	chatCache := cache.NewChatCache(cmdable)
	chatRepo := repository.NewChatRepo(chatDAO, chatCache)
	handler := initLLMHandler()
	chatService := service.NewChatService(chatRepo, handler)
	chatServer := grpc.NewChatServer(chatService)
	component := InitGrpcServer(chatServer)
	provider := InitSession()
	mockHandler := admin.NewMockHandler()
	invocationConfigDAO := dao.NewInvocationConfigDAO(db)
	invocationConfigRepo := repository.NewInvocationConfigRepo(invocationConfigDAO)
	bizConfigDAO := dao.NewBizConfigDAO(db)
	bizConfigRepository := repository.NewBizConfigRepository(bizConfigDAO)
	modelRepository := repository.NewModelRepository()
	invocationConfigService := service.NewInvocationConfigService(invocationConfigRepo, bizConfigRepository, modelRepository)
	invocationConfigHandler := admin.NewInvocationConfigHandler(invocationConfigService)
	bizConfigService := service.NewBizConfigService(bizConfigRepository)
	bizConfigHandler := admin.NewBizConfigHandler(bizConfigService)
	providerDao := dao.NewProviderDao(db)
	providerCache := cache.NewProviderCache(cmdable)
	providerRepo := repository.NewProviderRepo(providerDao, providerCache)
	providerService := initProvider(providerRepo)
	providerHandler := admin.NewProviderHandler(providerService)
	eginComponent := InitGin(provider, mockHandler, invocationConfigHandler, bizConfigHandler, providerHandler)
	app := &App{
		GrpcSever: component,
		GinServer: eginComponent,
	}
	return app
}
