// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/ecodeclub/ai-gateway-go/cmd/platform/ioc"
	"github.com/ecodeclub/ai-gateway-go/internal/admin"
	"github.com/ecodeclub/ai-gateway-go/internal/grpc"
	"github.com/ecodeclub/ai-gateway-go/internal/repository"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/cache"
	"github.com/ecodeclub/ai-gateway-go/internal/repository/dao"
	"github.com/ecodeclub/ai-gateway-go/internal/service"
	"github.com/ecodeclub/ai-gateway-go/internal/service/stream/fcall"
)

// Injectors from wire.go:

// InitApp 总体上这里的 app 都是从 platform 下的 ioc 复制过来的
// 只有一些需要 mock 的组件，才会作为参数传递进去
func InitApp(to TestOnly) *TestApp {
	db := InitDB()
	chatDAO := dao.NewChatDAO(db)
	cmdable := InitRedis()
	chatCache := cache.NewChatCache(cmdable)
	chatRepo := repository.NewChatRepo(chatDAO, chatCache)
	invocationConfigDAO := dao.NewInvocationConfigDAO(db)
	providerDAO := dao.NewProviderDAO(db)
	providerRepository := repository.NewProviderRepository(providerDAO)
	invocationConfigRepo := repository.NewInvocationConfigRepo(invocationConfigDAO, providerRepository)
	bizDAO := dao.NewBizConfigDAO(db)
	bizConfigRepository := repository.NewBizConfigRepository(bizDAO)
	quotaDAO := dao.NewQuotaDao(db)
	quotaRepo := repository.NewQuotaRepo(quotaDAO)
	quotaService := ioc.InitQuota(quotaRepo)
	providerService := ioc.InitProvider(providerRepository)
	chatService := service.NewChatService(chatRepo, invocationConfigRepo, bizConfigRepository, quotaService, providerService)
	orchestrator := to.Orchestrator
	chatServer := grpc.NewChatServer(chatService, orchestrator)
	component := ioc.InitGrpcServer(chatServer)
	provider := InitSession()
	mockHandler := admin.NewMockHandler()
	invocationConfigService := service.NewInvocationConfigService(invocationConfigRepo, bizConfigRepository, providerRepository)
	invocationConfigHandler := admin.NewInvocationConfigHandler(invocationConfigService)
	bizConfigService := service.NewBizConfigService(bizConfigRepository)
	bizConfigHandler := admin.NewBizConfigHandler(bizConfigService)
	providerHandler := admin.NewProviderHandler(providerService)
	eginComponent := InitGin(provider, mockHandler, invocationConfigHandler, bizConfigHandler, providerHandler)
	registry := fcall.NewFunctionCallRegistry()
	testApp := &TestApp{
		GrpcSever:        component,
		GinServer:        eginComponent,
		DB:               db,
		Rdb:              cmdable,
		funcCallRegistry: registry,
		ChatService:      chatService,
		QuotaService:     quotaService,
	}
	return testApp
}
